MASTER = 3
NODES = 1

Vagrant.configure("2") do |config|

  config.vm.box = 'centos/7'
  config.vm.provision "file", source: File.expand_path("../id_rsa.pub", __FILE__), destination: "~/.ssh/authorized_keys"
  config.ssh.insert_key = false
  config.ssh.private_key_path = [File.expand_path("../id_rsa", __FILE__), "~/.vagrant.d/insecure_private_key"]

  config.vm.provider 'virtualbox' do |v|
      v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end

  (1..MASTER).each do |master_id|
      config.vm.define "swarm-master#{master_id}" do |master|
        master.vm.hostname = "master#{master_id}"
        master.vm.network "private_network", ip: "192.168.77.#{20+master_id}"
        master.vm.box_check_update = false
        master.vm.provider "virtualbox" do |v|
          #play with this value
          v.memory = 2048
          v.cpus = 1
        end
      end
  end

  (1..NODES).each do |node_id|
      config.vm.define "swarm-node#{node_id}" do |node|
        node.vm.hostname = "node#{node_id}"
        node.vm.network "private_network", ip: "192.168.77.#{30+node_id}"
        node.vm.box_check_update = false
        node.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 1
        end
      end
  end

end
