version: "3"
services:
 nginx:
  image: nginx
  environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
  ports:
    - "9080:80"
  deploy:
    resources:
      limits:
        cpus: '0.2'
        memory: 128M
      reservations:
        cpus: '0.1'
        memory: 64M
      placement:
        constraints: [node.hostname == master1]
  logging:
    driver: "gelf"
    options:
      gelf-address: "udp://192.168.77.21:12201"
  networks:
    - devops
  volumes:
   - nginx:/usr/share/nginx/html

networks:
  devops:

volumes:
  nginx:
    driver_opts:
      type: none
      device:  "/home/vagrant/nginx"
      o: bind
