version: "3"
services:
 nginx:
  image: nginx
  environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
  ports:
    - "9080:80"
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 512M
      reservations:
        cpus: '0.2'
        memory: 256M
  logging:
    driver: "json-file"
    options:
      max-size: "500k"
      max-file: "5"
  restart: unless-stopped
  networks:
    - devops
  volumes:
   - nginx:/usr/share/nginx/html

networks:
  devops:

volumes:
  nginx:
    driver_opts:
      type: none
      device:  "/home/vagrant/nginx"
      o: bind
